<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Test_FB" Id="{43cff9cf-86da-42a1-85f2-5c49e1f5cfe2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Test_FB

VAR
nCounter	:	LINT;	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[nCounter := nCounter + 1;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>